name = "livekit-cf"
main = "./src/worker.ts"
compatibility_date = "2025-05-07"
compatibility_flags = [
  "enable_request_signal", # Needed for HTTP RPC streams
]

[build]
# Enable source maps for better debugging
command = ""

[[durable_objects.bindings]]
name = "SYNC_BACKEND_DO"
class_name = "SyncBackendDO"

[[durable_objects.bindings]]
name = "CLIENT_DO"
class_name = "LiveStoreClientDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncBackendDO", "LiveStoreClientDO"]

[[d1_databases]]
binding = "DB"
database_name = "pochi-livekit-events"
database_id = "29b297f5-75ee-437e-8a9a-94ae9de0fc0a"


[vars]
# should be set via CF dashboard (as secret)
# ADMIN_SECRET = "..."
# SYNC_BACKEND_URL = "http://localhost:8787"

[triggers] # bootstrap ping every minute
crons = ["*/1 * * * *"]
